### ISSUE TITLE
[Idea] Art for intermediary steps

### ISSUE THREAD

**Issue by wntiv-main** [mame/quine-relay#154]
While the initial source code makes ascii art, it could be cool if all of the other steps also made some kind of art (especially cool if this could play out into some kind of animation), at least in the languages where this is possible (i.e. text languages where whitespace is not significant etc.)

**Comment by mame** [comment]
Thank you for the idea. That is easy in theory, but difficult in engineering. Some languages have difficulty dealing with programs larger than they currently are for a variety of reasons: limited number of characters available in the program, slow execution, etc. In order to animate, additional data must be added for this purpose. This is the trade-off for the number of languages. I would prioritize the number of languages here.
