### ISSUE TITLE
How long did it take you?

### ISSUE THREAD

**Issue by tsvetann** [mame/quine-relay#60]
How long did it take you?

**Comment by ypid** [comment]
Good question. I am also curious :smile:

**Comment by LiChenda** [comment]
It's amazing!

**Comment by mame** [comment]
Infinity, of course.  I wrote the first program in Ruby. Then I wrote the second program in Ruby that produces the first one through 100 languages.  Then I wrote the third program that produces the second one.  Repeated until the fixed point.  What you see is ∞th program beyond the world line.

**Comment by seclorum** [comment]
What I see is a lunatic who is going to drive me mad and thus cure me of sanity.  Endlessly!  Thanks!

**Comment by harshjain30** [comment]
Nothing is more inspirational than insanity

**Comment by kurtlove** [comment]
Yusuke Endoh,

Wow....now that is cool to see someone today doing that...I'm am actual living dinosaur who started out on the ARPAnet in 1981. I've actually programmed in a fair number of the languages on your list, even some of the very most obscure on the list often just for the "what the fuck" of it, to see how they worked, or even just "looked."Of the few languages that I did not see in your list of 100 that would all qualify as being obscure are Inform, Shakespeare, and Bliss.

Even today, APL is still one of my favorite to just "screw with someone's head" languages -- if I can get someone to try it out. Dutch computer scientist Edsger Dijkstra said: "APL is a mistake, carried through to perfection. It is the language of the future for the programming techniques of the past: it creates a new generation of coding bums." Here's the ENTIRE Game of Life in, of course, one line of APL:

                        life←{↑1 ω∨.∧3 4=+/,¯1 0 1∘.⊖¯1 0 1∘.⌽⊂ω}

LISP is the winner, LISP is it, the language of languages where objects of objects of objects are just a lambda of lambda of lambda away so that you do not need to use a CLOS, just macros of macros of macros. It is my bread and butter everyday coding 'go-to' language -- (defun pun (intended)). 

Programmer's who do not know LISP do not know programming. Period. End of Gestapo. 

I do so pity all those poor schmucks in JAVA factories in Bangalore cutting and pasting the same JAVA over and over and over and over and over and over into the same program just to get some HTML out to a browser. And the nightmare is that they likely don't even know LISP exists. 

McCarthy is turning in his grave, laughing. 

I'm glad to have found you, to know you are out there. Keep going kid and you will always own each and every world you make in code.

If you'd like help translating and publishing your book from Japanese into English -- from there, it would be easy to do a German edition! German's are all about craft, so German programmers would love your book. I've just started being a small indie publisher, and can get your book out in print in English (yes, I have a local Japanese technical translator that I know personally) -- so, drop me a line: let's talk.

Yours Respectfully,

-=KuRt=-

**Comment by ockham** [comment]
> If you'd like help translating and publishing your book from Japanese into English -- from there, it would be easy to do a German edition!

I respectfully suggest that from German, it should then be translated into Russian. From Russian, to French. From French, to Spanish. From Spanish, to Arabic. From Arabic, to ...
... And finally, from Chinese, to Japanese.

**Comment by oxidizeddreams** [comment]
This has been a wonderful rabbit hole to venture down. I thank you.

**Comment by umutozdemir97** [comment]
confusion

**Comment by janfilips** [comment]
Mad. Just mad! :) :) :) :) :) :) :)

**Comment by sabvdf** [comment]
> > If you'd like help translating and publishing your book from Japanese into English -- from there, it would be easy to do a German edition!
> 
> I respectfully suggest that from German, it should then be translated into Russian. From Russian, to French. From French, to Spanish. From Spanish, to Arabic. From Arabic, to ... ... And finally, from Chinese, to Japanese.

You missed one detail there: put the languages to translate through in alphabetical order 😢 😄

**Comment by fref** [comment]
I'd love to read your book, but I haven't even reach JLPT5 :'(
